export const Resource = [
	['bg', 'res/images/bg.jpg'],
	['bullet', 'res/images/bullet.png'],
	['enemy', 'res/images/enemy.png'],
	['hero', 'res/images/hero.png'],
	['explosion1', 'res/images/explosion1.png'],
	['explosion2', 'res/images/explosion2.png'],
	['explosion3', 'res/images/explosion3.png'],
	['explosion4', 'res/images/explosion4.png'],
	['explosion5', 'res/images/explosion5.png'],
	['explosion6', 'res/images/explosion6.png'],
	['explosion7', 'res/images/explosion7.png'],
	['explosion8', 'res/images/explosion8.png'],
	['explosion9', 'res/images/explosion9.png'],
	['explosion10', 'res/images/explosion10.png'],
	['explosion11', 'res/images/explosion11.png'],
	['explosion12', 'res/images/explosion12.png'],
	['explosion13', 'res/images/explosion13.png'],
	['explosion14', 'res/images/explosion14.png'],
	['explosion15', 'res/images/explosion15.png'],
	['explosion16', 'res/images/explosion16.png'],
	['explosion17', 'res/images/explosion17.png'],
	['explosion18', 'res/images/explosion18.png'],
	['explosion19', 'res/images/explosion19.png'],
	['common', 'res/images/common.png']
]